name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Image
      run: sudo docker pull priyanshoe/tbd-core:latest

    - name: Delete old Docker container
      run: sudo docker rm -f tbd-core-container || true
    
    - name: Delete old Docker image
      run: |
        old_image_id=$(sudo docker images priyanshoe/tbd-core --format "{{.ID}}" | tail -n +2)
        if [ -n "$old_image_id" ]; then
          sudo docker rmi -f $old_image_id
        fi

    - name: Run docker container
      run: sudo docker run -d -p 3000:3000 --name tbd-core-container priyanshoe/tbd-core:latest
